FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY join.py .

ENV INPUT_DIR=/data/input
ENV OUTPUT_DIR=/data/output

CMD ["python", "join.py"]
